os.system("pkg update -y")
os.system("pkg upgrade -y")
os.system("pkg install git -y")
os.system("pkg install python -y")
os.system("pkg install python2 -y")
os.system("pip install requests")
os.system("pip install bs4")
os.system("pip install mechanize")
os.system("pip install httpx")
os.system("pip install instaloader")
