os.system("pkg update")
os.system("pkg upgrade")
os.system("pkg install git")
os.system("pkg install python")
os.system("pkg install python2")
os.system("pip install requests")
os.system("pip install bs4")
os.system("pip install mechanize")
os.system("pip install httpx")
os.system("pip install instaloader")
